version: "3"

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            - "8088:80"
            - "443:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4406:3306"
        environment:
            MYSQL_DATABASE: comicmaker
            MYSQL_ROOT_PASSWORD: passwd
            MYSQL_PASSWORD: passwd
            MYSQL_USER: comicmakeruser
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
            - ./mysql/database:/docker-entrypoint-initdb.d
        networks:
            - laravel

    php:
        build: 
            args:
                user: elfeqy
                uid: 1000
            context: .
            dockerfile: Dockerfile
        
        image: digitalocean.com/php
        container_name: php
        restart: unless-stopped
        tty: true
        volumes:
            - ./src:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www/html
        ports:
            - 9000:9000
        networks: 
            - laravel
    
    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks: 
            - laravel
    
    npm:
        image: node:14.17
        container_name: npm
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks: 
            - laravel

    artisan:
        build:
            args:
                user: elfeqy
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: artisan
        volumes: 
            - ./src:/var/www/html
        depends_on: 
            - mysql
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']
        networks: 
            - laravel


#Docker Networks
networks: 
    laravel:
        driver: bridge

#Volumes
volumes:
    dbdata:
      driver: local
        